name       : pimcommon
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/pimcommon-17.08.2.tar.xz : 0b847e6ae3ba80297e286f33e650bd1dbf05f48301b91347ac9c4c5f0a235006
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications.
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - grantlee-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
