name       : pimcommon
version    : 21.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/pimcommon-21.04.1.tar.xz : 7dbed3b542f7a1c8f78fa6a96b8687fa460c6264fb9cc85b372ca16c723c11ba
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kio-devel
    - kimap-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - purpose-devel
rundeps    :
    - devel :
        - kimap-devel
        - akonadi-contacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
