name       : pimcommon
version    : 20.12.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/pimcommon-20.12.3.tar.xz : 0b9a0ad2128f41aa5de06dc2a9b28d631ca6a47a5fcf26e5320045f08228fea1
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kio-devel
    - kimap-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - purpose-devel
rundeps    :
    - devel :
        - kimap-devel
        - akonadi-contacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
