name       : pimcommon
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/pimcommon-17.04.1.tar.xz : a26b12e9c36c3b8e859ac0e4d7c88c0347d28905bf47445e6cfdfde36a42a79b
license    : 
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications.
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - grantlee-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
    - karchive-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
