name       : pimcommon
version    : 20.08.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/pimcommon-20.08.3.tar.xz : 98da28f3ba0793c3699e8185d45864257c767a6805ad06c9fcb2172f223df456
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - libboost-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
