name       : pimcommon
version    : 20.04.2
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/pimcommon-20.04.2.tar.xz : cc9aff8c38a9ea921645bab06409297fe2d930bfa9880dc12af626ce239bda3f
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - grantlee-devel
    - karchive-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - libboost-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
