name       : pimcommon
version    : 22.04.2
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/pimcommon-22.04.2.tar.xz : e141cd0ed14be489d93c784e283db0d3f84fb01f17017a27368b487112de5505
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kio-devel
    - kimap-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - purpose-devel
rundeps    :
    - devel :
        - kimap-devel
        - akonadi-contacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
