name       : pimcommon
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/pimcommon-17.12.2.tar.xz : 0ac956cb7cc8b06781d75103eff5f76205e4f52533f5b832711f8b06b5b02f3b
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications.
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - grantlee-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
