name       : pimcommon
version    : 23.04.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/pimcommon-23.04.0.tar.xz : 3446344b154fe444848efea27368be6da8e21aca30a9c6b03d9a078ead6681ac
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kio-devel
    - kimap-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - libkdepim-devel
    - purpose-devel
rundeps    :
    - devel :
        - kimap-devel
        - akonadi-contacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
