name       : pimcommon
version    : 17.12.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/pimcommon-17.12.3.tar.xz : 78c6194295b97d3759388d19cba12937a02b639d7f68ff78c3c565c3a9435bf9
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications.
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - grantlee-devel
    - karchive-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
