name       : pimcommon
version    : 20.12.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/pimcommon-20.12.0.tar.xz : 54c6e51730bc10c67bade70a67f2500aa4fe4d2db32572bff3fecc4f7ab85c5c
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - grantlee-devel
    - grantleetheme-devel
    - karchive-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - libboost-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
