name       : pimcommon
version    : 20.12.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/pimcommon-20.12.1.tar.xz : a7644e6a49b5fc29ff729ff688b841031b6d5d0f90e61e06eddb62ad77ddaaf0
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - karchive-devel
    - kcalendarcore-devel
    - kcmutils-devel
    - kcontacts-devel
    - kldap-devel
    - kio-devel
    - kimap-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - purpose-devel
rundeps    :
    - devel :
        - kimap-devel
        - akonadi-contacts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
