name       : pimcommon
version    : 20.04.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/pimcommon-20.04.1.tar.xz : f2640bf49d72ad894be28de4545804f4de27e79dbe45e236959e47c2cbc68e96
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Pimcommon library, used by several KDE PIM applications
description: |
    Common libraries for KDE PIM.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - grantlee-devel
    - karchive-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - kiconthemes-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kmime-devel
    - knewstuff-devel
    - kpimtextedit-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libkdepim-devel
    - libboost-devel
    - purpose-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
